#!/bin/bash

for x in `ls files`
do
    rm -f ~/.$x
    cp files/$x ~/.$x
done

platform=`uname`
if [[ "$platform" == 'Darwin' ]]; then
    for x in `ls osx`
    do
        rm -f ~/.$x
        cp osx/$x ~/.$x
    done
else
    for x in `ls linux`
    do
        rm -f ~/.$x
        cp linux/$x ~/.$x
    done
fi

echo now change your ~/.gitconfig to your github info!